default:
    threshold: 80

node:
    n0:
        kind: 0 # normal
        name: n0
        validators:
            - n1
            - n2
            - n3
            - n4
        messages:
            - message from n0
            - message2 from n0
    n1:
        kind: 0 # normal
        name: n1
        validators:
            - n0
            - n2
            - n3
            - n4
    n2:
        kind: 0 # normal
        name: n2
        validators:
            - n0
            - n1
            - n3
            - n4
    n3:
        kind: 0 # normal
        name: n3
        validators:
            - n0
            - n1
            - n2
            - n4
    n4:
        kind: 0 # normal
        name: n4
        validators:
            - n0
            - n1
            - n2
            - n3
        messages:
            - message3 from n4
            - message4 from n4
